export const GET_ALL_PROJECT_CATEGORY_API = "GET_ALL_PROJECT_CATEGORY_API";
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
export const CREATE_PROPJECT_API = "CREATE_PROPJECT_API";
export const GET_LIST_PROJECT_API = "GET_LIST_PROJECT_API";
export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
export const SHOW_MODAL_EDIT_AND_COMPONENT = "SHOW_MODAL_EDIT_AND_COMPONENT";
export const HIDE_MODAL_EDIT = "HIDE_MODAL_EDIT";
export const SET_SUBMIT_EDIT = "SET_SUBMIT_EDIT";
export const UPDATE_PROJECT_API = "UPDATE_PROJECT_API";
export const DELETE_PROJECT_API = "DELETE_PROJECT_API";
export const REMOVE_USER_FROM_PROJECT = "REMOVE_USER_FROM_PROJECT";
export const GET_PROJECT_DETAIL_API = "GET_PROJECT_DETAIL_API";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";
export const GET_ALL_PROPJECT_API = "GET_ALL_PROPJECT_API";
export const GET_LIST_PROJECT_PART_CREATE_TASK_API =
  "GET_LIST_PROJECT_PART_CREATE_TASK_API";
