export const CREATE_TASK_API = "CREATE_TASK_API";
export const GET_TASK_DETAIL_API = "GET_TASK_DETAIL_API";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const UPDATA_STATUS_TASK_API = "UPDATA_STATUS_TASK_API";
export const CHANGE_ASSIGNESS = "CHANGE_ASSIGNESS";
export const REMOVE_USER_ASSIGNESS = "REMOVE_USER_ASSIGNESS";
export const UPDATE_TASK_API = "UPDATE_TASK_API";

export const CHANGE_PROPERTY_IN_TASK = "CHANGE_PROPERTY_IN_TASK";
