export const GET_USER_API = "GET_USER_API";
export const GET_USERS = "GET_USERS";
export const ASSIGN_USER_PROjECT = "ASSIGN_USER_PROjECT";
export const GET_USER_BY_PROJECT_ID_API = "GET_USER_BY_PROJECT_ID_API";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";
export const SIGN_UP_API = "SIGN_UP_API";
export const DELETE_USER_API = "DELETE_USER_API";
export const UPDATE_USER_API = "UPDATE_USER_API";
